[tool.poetry]
name = "marketflow"
version = "1.1.1"
description = "Access to African, American, European and Asian market data for financial analysis, scientific study and to provide a decision-making basis to investors."
authors = ["Olabiyi Aurel Géoffroy ODJO <odjoaurel@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "marketflow", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
marketflow = ["__data__/*.db"]